### ISSUE TITLE
Markup in Markdown

### ISSUE THREAD

**Issue by Ryuno-Ki** [Sabayon/sabayon-website-next#12]
Looking at Markdown files in content directory (for example, [download.md](https://raw.githubusercontent.com/Sabayon/sabayon-website-next/7406b24e8f125ef70b8dca2cacddaff6f2670f79/content/download.md)) I observed, that it's heavily tangled with Markup (read: HTML).

This way you're bound to Twitter Bootstrap.

Ideally, content authors should not worry about the markup. I'm working on this issue currently.

**Comment by Ryuno-Ki** [comment]
I have a proposal how I would rewrite download.md at https://github.com/Ryuno-Ki/sabayon-website-next/commit/2ea5841b075d2d43a8f998aad70b5af0bcba6329 and https://github.com/Ryuno-Ki/sabayon-website-next-theme/commit/33c92d4d79168ab1abc91ad9def5f5a3bb1860cd

I suggest either to write several layouts for the design if you want to go with Bootstrap (will become awkward, since the content is likely in the frontmatter to be injected in the correct columns) or look for a flexbox-based layout (like in the proposal).

**Comment by mudler** [comment]
+1 (sorry, didn't see that, github notifications sucks), do a PR i'll be glad to review and merge it

**Comment by Ryuno-Ki** [comment]
Have a look at #14 and https://github.com/Sabayon/sabayon-website-next-theme/pull/2
