### ISSUE TITLE
Installing with errors

### ISSUE THREAD

**Issue by Ryuno-Ki** [Sabayon/sabayon-website-next#3]
Steps to reproduce:
1. Fork the repo
2. Clone your fork to your machine (Last commit: `0f3260ee2437db166afe79ae8fc1ff847cc94e0f`)
3. `$sudo equo i hugo` (installed `www-apps/hugo-0.15_pre20151102` on Sabayon, details below.
4. `cd` into cloned fork, then 

``` bash
$ hugo
ERROR: 2016/03/24 Unable to render [partials/header.html theme/partials/header.html]
ERROR: 2016/03/24 Expecting to find a template in either the theme/layouts or /layouts in one of the following relative locations [partials/header.html theme/partials/header.html]
ERROR: 2016/03/24 Unable to render [partials/footer.copyright.html theme/partials/footer.copyright.html]
ERROR: 2016/03/24 Expecting to find a template in either the theme/layouts or /layouts in one of the following relative locations [partials/footer.copyright.html theme/partials/footer.copyright.html]
ERROR: 2016/03/24 Unable to render [partials/footer.html theme/partials/footer.html]
ERROR: 2016/03/24 Expecting to find a template in either the theme/layouts or /layouts in one of the following relative locations [partials/footer.html theme/partials/footer.html]
0 draft content
0 future content
17 pages created
0 paginator pages created
20 tags created
8 categories created
in 78 ms
```

Are those errors critical?

Details about my machine:

``` bash
$ uname -a
Linux t520 4.3.0-sabayon #1 SMP Wed Dec 16 22:02:39 UTC 2015 x86_64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz GenuineIntel GNU/Linux
```

**Comment by Ryuno-Ki** [comment]
Yupp, they're refenced in `layouts/index.html` but not checked in. Moah, I cannot even start hacking on CSS in order to address #2 :-/

**Comment by mudler** [comment]
I'm sorry for that, i had no time to update the readme with the new way to compile/run the project.

The theme now is in a separate repository, so we can inherit and use it in other websites as well (while we rework on them): https://github.com/Sabayon/sabayon-website-next-theme

to build the website you just have to run this:

`HUGO_THEME=https://github.com/Sabayon/sabayon-website-next-theme make build`

instead, if you want hack on it, you have to create a "themes" directory inside the repository, and clone our theme:

`git clone https://github.com/Sabayon/sabayon-website-next-theme themes/website-next
`

and then you can run:

`hugo server -w --theme=website-next`
