### ISSUE TITLE
Categories are broken

### ISSUE THREAD

**Issue by mudler** [Sabayon/sabayon-website-next#39]
[https://next.sabayon.org/categories/sabayon/](https://next.sabayon.org/categories/sabayon/)
![2016-10-29-100201_1920x1080_scrot](https://cloud.githubusercontent.com/assets/2420543/19828144/0539642c-9dbf-11e6-9528-7a2391005eac.png)

**Comment by Ryuno-Ki** [comment]
The link yields 404. How do you navigate there?

**Comment by mudler** [comment]
ops, corrected url

**Comment by Ryuno-Ki** [comment]
Works now. I need to figure out, which template is responsible. The markup around is missing (c.f. latest merged PRs).

**Comment by mudler** [comment]
fixed by dropping categories and tags from custom pages as for now

**Comment by Ryuno-Ki** [comment]
Reverted 497f71f0ba612930727c73a8bd5052b6e03b4e53 and lgtm. HEAD at bd80bc18d15be1a3be42e34a3285f4003d9b1981
![sabayon-categories](https://cloud.githubusercontent.com/assets/3097194/19832724/34ffc1a2-9e2c-11e6-8943-61f11e1ce4cb.png)

**Comment by Ryuno-Ki** [comment]
Fixed by #46
