### ISSUE TITLE
Navbar broken in download section

### ISSUE THREAD

**Issue by mudler** [Sabayon/sabayon-website-next#40]
[https://next.sabayon.org/desktop/](https://next.sabayon.org/desktop/)
![2016-10-29-100443_1920x1080_scrot](https://cloud.githubusercontent.com/assets/2420543/19828158/4e84fb96-9dbf-11e6-930d-d2a6ff4a971f.png)

**Comment by Ryuno-Ki** [comment]
Define "broken". Headroom does not kick in? Probably `id="top-nav"` is missing on `<nav>`.

**Comment by mudler** [comment]
attached the image to define broken :)

**Comment by Ryuno-Ki** [comment]
I can hardly tell what you want to tell with it. Henxe I asked. If I saw ut correctly, I saw a white text overlapping the content, which usually stemmed from the navbar.

**Comment by mudler** [comment]
fixed it

**Comment by mudler** [comment]
this seems to happens again now, but in another way, could be related: when you scroll down the page, the navbar is hiding part of the top page

**Comment by mudler** [comment]
Great! Thanks!
