### ISSUE TITLE
Downloads page icons don't link

### ISSUE THREAD

**Issue by jcfrosty** [Sabayon/sabayon-website-next#49]
On the downloads page. the icons aren't actually links to Desktop, Server, Cloud editions. to download you must point to the text or to the left/right of the image. Clicking the image should also link to the appropriate download.

**Comment by mudler** [comment]
@Ryuno-Ki IIRC  that used to work, right? 

Can you look at that? thanks :)

**Comment by Ryuno-Ki** [comment]
Sure, I'm looking into it (meh, my mail reply did not make it here).

On https://next.sabayon.org/download/ the icons are linked.
However, on https://next.sabayon.org/desktop/ they are not. I'm writing a PR for the latter.

**Comment by mudler** [comment]
Thanks! :) i'll rebuild and merge today

**Comment by jcfrosty** [comment]
Thanks guys!
