### ISSUE TITLE
Copyright notice is one year out-of-date

### ISSUE THREAD

**Issue by fusion809** [Sabayon/sabayon-website-next#53]
Hi,

I've noticed that the copyright notice, that is:

> © 2004-2016 Sabayon Promotion (CF: 93018620224).
> Unless otherwise stated, content on this page is licensed under a Creative Commons Attribution-ShareAlike 3.0 License.
> Linux is a registered trademark of Linus Torvalds.
> All other trademarks are the property of their respective owners.

is one year out-of-date, should be:

> © 2004-2017 Sabayon Promotion (CF: 93018620224).
> Unless otherwise stated, content on this page is licensed under a Creative Commons Attribution-ShareAlike 3.0 License.
> Linux is a registered trademark of Linus Torvalds.
> All other trademarks are the property of their respective owners.

I searched this repository for "Sabayon Promotion" and "2016" in the hope to find where this copyright notice is so that I can update it myself and submit a pull request but I can't find it so I'm left having to open this issue instead.

Thanks for your time,
Brenton

**Comment by Ryuno-Ki** [comment]
In https://github.com/Sabayon/sabayon-website-next/blob/master/layouts/index.html you can see that `footer.copyright` is included. Near the end of the file.

So copyright is maintained in https://github.com/Sabayon/sabayon-website-next-theme/blob/master/layouts/partials/footer.copyright.html (again, near end of file).

**Comment by Ryuno-Ki** [comment]
I hadn't found time to work on the homepage this year, since I switched my job at beginning of Feb.

PR is very welcome :-)

**Comment by jcfrosty** [comment]
Can we close this issue if this has been fixed?
