### ISSUE TITLE
Link to Spinbase broken on release pages

### ISSUE THREAD

**Issue by Ryuno-Ki** [Sabayon/sabayon-website-next#67]
Using ScreamingFrog SEO-Spider to watch out for 404s, I've learned, that the link to our Spinbase is broken.

You can find the link for example in the [Latest Monthly Release: Sabayon 15.12](https://www.sabayon.org/release/latest-monthly-release-sabayon-1512/).

That, is update the link to VagrantCloud/Atlas in https://github.com/Sabayon/sabayon-website-next/blob/master/content/release/latest-monthly-release-sabayon-1512.md#vagrant-images and Sabayon on Atlas (VagrantCloud) in https://github.com/Sabayon/sabayon-website-next/blob/master/content/release/latest-monthly-release-sabayon-1512.md#download-links

All files in release directory are affected.

**Comment by mudler** [comment]
~~Those are comments!~~ please stop opening massive issues using some automated tool.
